/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as blurhash from "../blurhash.js";
import type * as files from "../files.js";
import type * as gemini from "../gemini.js";
import type * as http from "../http.js";
import type * as payments from "../payments.js";
import type * as plans from "../plans.js";
import type * as playht from "../playht.js";
import type * as podcasts from "../podcasts.js";
import type * as stats from "../stats.js";
import type * as stripe from "../stripe.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  blurhash: typeof blurhash;
  files: typeof files;
  gemini: typeof gemini;
  http: typeof http;
  payments: typeof payments;
  plans: typeof plans;
  playht: typeof playht;
  podcasts: typeof podcasts;
  stats: typeof stats;
  stripe: typeof stripe;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
